import {notFound} from "next/navigation";
import {Clock,ExternalLink,MapPin,Phone} from "lucide-react";
import {businesses} from "@/lib/data";
import {getBusiness} from "@/lib/businesses";
import {getLiveAds} from "@/lib/advertising";
import {DealCard} from "@/components/cards";
import {SponsoredPlacement} from "@/components/sponsored-placement";
import {getDeals} from "@/lib/content";
import {cleanOptional,isPhysicalBusiness} from "@/lib/listings";

export function generateStaticParams(){return businesses.map(b=>({slug:b.slug}))}
export default async function Page({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params,b=await getBusiness(slug);if(!b)notFound();
  const [current,enhanced]=await Promise.all([getDeals().then(items=>items.filter(d=>d.businessId===b.id)),getLiveAds("business_profile",b.id)]),phone=cleanOptional(b.phone),website=cleanOptional(b.website),address=isPhysicalBusiness(b)?cleanOptional(b.address):undefined;
  return <><section className="border-b border-cream/10 bg-pine"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p className="text-sm font-bold uppercase tracking-wider text-forest">{b.category} · Free directory listing</p><h1 className="mt-3 max-w-3xl font-display text-4xl text-cream md:text-6xl">{b.name}</h1></div></section>
  {enhanced.length>0&&<section className="mx-auto max-w-7xl px-5 pt-12 lg:px-8"><SponsoredPlacement campaign={enhanced[0]} variant="profile"/></section>}
  <section className="mx-auto grid max-w-7xl gap-10 px-5 py-14 md:grid-cols-[1.5fr_1fr] lg:px-8"><div><h2 className="font-display text-3xl">About</h2><p className="mt-5 text-lg leading-8 text-ink/70">{b.description}</p><div className="mt-8 flex flex-wrap gap-3">{phone&&<a href={`tel:${phone}`} className="inline-flex min-h-12 items-center gap-2 border border-cream/20 bg-pine px-5 font-bold text-cream"><Phone size={18}/> Call</a>}{website&&<a href={website} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center gap-2 border border-cream/20 px-5 font-bold"><ExternalLink size={18}/> Website</a>}{address&&<a href={`https://maps.google.com/?q=${encodeURIComponent(address)}`} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center gap-2 border border-cream/20 px-5 font-bold"><MapPin size={18}/> Directions</a>}</div>{current.length>0&&<div className="mt-14"><h2 className="mb-5 font-display text-3xl">Current deals</h2>{current.map(x=><DealCard item={x} business={b} key={x.id}/>)}</div>}</div>
  <aside className="h-fit border border-cream/10 bg-white p-6"><h2 className="font-display text-2xl">Listing details</h2><div className="mt-5 space-y-5 text-sm">{address&&<p className="flex gap-3"><MapPin className="shrink-0 text-forest" size={20}/>{address}</p>}{!address&&b.locationType==="service_area"&&<p className="text-ink/65">Service-area business serving Heber-Overgaard; no public storefront.</p>}{!address&&b.locationType==="online"&&<p className="text-ink/65">Online business; no public storefront.</p>}{phone&&<p className="flex gap-3"><Phone className="shrink-0 text-forest" size={20}/>{phone}</p>}<div className="flex gap-3"><Clock className="mt-0.5 shrink-0 text-forest" size={20}/><div>{b.hours?<><p className="whitespace-pre-line font-medium leading-6">{b.hours}</p>{b.hoursVerifiedAt&&<p className="mt-2 text-xs text-ink/50">Verified {new Date(`${b.hoursVerifiedAt}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}</p>}{b.hoursSource&&<a href={b.hoursSource} target="_blank" rel="noreferrer" className="mt-1 inline-block text-xs font-bold text-forest underline">Hours source ↗</a>}</>:<p>Hours are not reliably published — call or check the business website before visiting.</p>}</div></div></div><p className="mt-6 border-t border-cream/10 pt-5 text-xs leading-5 text-ink/55">Hours and services can change seasonally or on holidays. Confirm directly before making a special trip.</p></aside></section></>
}
