"use server";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {getSupabase} from "@/lib/supabase/server";
import {attractions,trails} from "@/lib/data";

const slugify=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
async function db(){const client=await getSupabase();if(!client)throw new Error("Supabase is not configured");const {data:{user}}=await client.auth.getUser();if(!user)redirect("/admin/login");return client}
async function imageUrl(client:Awaited<ReturnType<typeof db>>,form:FormData,folder:string){const file=form.get("image_file");const current=String(form.get("current_image")||"");const typed=String(form.get("image_url")||"").trim();if(!(file instanceof File)||file.size===0)return typed||current||null;if(file.size>5*1024*1024)throw new Error("Images must be 5 MB or smaller");if(!["image/jpeg","image/png","image/webp","image/gif"].includes(file.type))throw new Error("Use a JPG, PNG, WebP, or GIF image");const extension=(file.name.split(".").pop()||"jpg").toLowerCase().replace(/[^a-z0-9]/g,"");const path=`${folder}/${crypto.randomUUID()}.${extension}`;const {error}=await client.storage.from("content-images").upload(path,file,{contentType:file.type,upsert:false});if(error)throw new Error(error.message);return client.storage.from("content-images").getPublicUrl(path).data.publicUrl}

export async function saveAttraction(f:FormData){const c=await db(),id=String(f.get("id")||""),name=String(f.get("name")||"").trim();const row={name,slug:slugify(String(f.get("slug")||name)),category:String(f.get("category")||"Recreation"),description:String(f.get("description")||""),website:String(f.get("website")||"")||null,cost_type:String(f.get("cost_type")||"Free"),image_url:await imageUrl(c,f,"attractions"),active:f.get("active")==="on",updated_at:new Date().toISOString()};const r=id?await c.from("attractions").update(row).eq("id",id):await c.from("attractions").insert(row);if(r.error)throw new Error(r.error.message);revalidatePath("/things-to-do");revalidatePath("/");redirect("/admin/attractions?saved=1")}
export async function saveTrail(f:FormData){const c=await db(),id=String(f.get("id")||""),name=String(f.get("name")||"").trim();const row={name,slug:slugify(String(f.get("slug")||name)),description:String(f.get("description")||""),distance:String(f.get("distance")||"Varies"),difficulty:String(f.get("difficulty")||"Moderate"),estimated_duration:String(f.get("duration")||"Varies"),activity_type:String(f.get("activity_type")||"Hiking"),family_friendly:f.get("family_friendly")==="on",image_url:await imageUrl(c,f,"trails"),active:f.get("active")==="on",updated_at:new Date().toISOString()};const r=id?await c.from("trails").update(row).eq("id",id):await c.from("trails").insert(row);if(r.error)throw new Error(r.error.message);revalidatePath("/trails");revalidatePath("/");redirect("/admin/trails?saved=1")}
export async function saveEvent(f:FormData){const c=await db(),id=String(f.get("id")||""),name=String(f.get("name")||"").trim();const row={name,slug:slugify(String(f.get("slug")||name)),description:String(f.get("description")||""),start_date:String(f.get("start_date")),end_date:String(f.get("end_date")||"")||null,start_time:String(f.get("start_time")||"")||null,location:String(f.get("location")||""),address:String(f.get("address")||""),website:String(f.get("website")||"")||null,category:String(f.get("category")||"Community"),image_url:await imageUrl(c,f,"events"),active:f.get("active")==="on",updated_at:new Date().toISOString()};const r=id?await c.from("events").update(row).eq("id",id):await c.from("events").insert(row);if(r.error)throw new Error(r.error.message);revalidatePath("/events");revalidatePath("/");redirect("/admin/events?saved=1")}
export async function importRecreation(){const c=await db();const a=attractions.map(x=>({name:x.name,slug:x.slug,category:x.category,description:x.description,image_url:x.image,website:x.website||null,cost_type:x.costType,featured:!!x.featured,active:true}));const t=trails.map(x=>({name:x.name,slug:x.slug,description:x.description,distance:x.distance,difficulty:x.difficulty,estimated_duration:x.duration,activity_type:x.activityType,family_friendly:x.familyFriendly,image_url:x.image,active:true}));const [ar,tr]=await Promise.all([c.from("attractions").upsert(a,{onConflict:"slug"}),c.from("trails").upsert(t,{onConflict:"slug"})]);if(ar.error||tr.error)throw new Error(ar.error?.message||tr.error?.message);revalidatePath("/things-to-do");revalidatePath("/trails");redirect("/admin/attractions?imported=1")}
export async function updateInquiry(f:FormData){const c=await db();const {error}=await c.from("business_inquiries").update({status:String(f.get("status"))}).eq("id",String(f.get("id")));if(error)throw new Error(error.message);revalidatePath("/admin/inquiries")}
