"use client";
import {useMemo,useState} from "react";
import Link from "next/link";

type State="idle"|"sending"|"saved"|"error";
const input="mt-2 h-12 w-full border border-cream/20 px-3 font-normal";
const Required=()=> <span className="ml-1 text-red-400" aria-hidden="true">*</span>;
const checks=[
  ["authorized","I own this property or am authorized to advertise it."],
  ["content_rights","I have permission to submit and authorize TownGuide's use of all uploaded photos and written content."],
  ["compliance","This rental complies with applicable licensing, registration, tax, HOA, safety, and short-term-rental requirements."],
  ["advertising_only","I understand TownGuide provides advertising only and is not a property manager, booking service, broker, or party to reservations."],
  ["booking_responsibility","I understand availability, pricing, payments, refunds, cancellations, guest communication, and disputes are handled by the owner and booking platform."],
] as const;
export function VacationRentalForm({priceCents}:{priceCents:number}){
  const [state,setState]=useState<State>("idle"),[error,setError]=useState(""),[files,setFiles]=useState<File[]>([]),[featured,setFeatured]=useState(0),[submissionId]=useState(()=>crypto.randomUUID());
  const previews=useMemo(()=>files.map(file=>({file,url:URL.createObjectURL(file)})),[files]);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setState("sending");setError("");const form=new FormData(event.currentTarget);files.forEach(file=>form.append("photos",file));form.set("featured_index",String(featured));try{const response=await fetch("/api/vacation-rentals",{method:"POST",body:form}),result=await response.json() as {checkoutUrl?:string;error?:string};if(!response.ok){setError(result.error||"Submission failed.");setState("error");return}if(result.checkoutUrl){window.location.assign(result.checkoutUrl);return}setState("saved");}catch{setError("We couldn't reach the server. Please try again.");setState("error");}}
  if(state==="saved")return <div className="border border-forest/30 bg-white p-10 text-center"><h2 className="font-display text-3xl">Your property was saved.</h2><p className="mt-3">We’ll contact you with a secure payment link. Payment does not publish the listing; every property is reviewed before approval.</p></div>;
  return <form onSubmit={submit} className="grid gap-5 border border-cream/10 bg-white p-6 shadow-soft md:grid-cols-2" encType="multipart/form-data">
    <input type="hidden" name="submission_id" value={submissionId}/><input className="hidden" aria-hidden="true" tabIndex={-1} name="company_fax" autoComplete="off"/>
    <div className="md:col-span-2"><h2 className="font-display text-3xl">Owner or property manager</h2><p className="mt-2 text-sm text-ink/60">Private administration information. It will never appear on the public listing.</p><p className="mt-2 text-sm font-bold text-red-400"><span aria-hidden="true">*</span> Required field</p></div>
    <label className="text-sm font-bold">Name<Required/><input className={input} name="owner_name" required maxLength={120}/></label>
    <label className="text-sm font-bold">Email<Required/><input className={input} name="owner_email" type="email" required maxLength={254}/></label>
    <label className="text-sm font-bold">Phone<Required/><input className={input} name="owner_phone" type="tel" required maxLength={50}/></label>
    <label className="text-sm font-bold">Preferred contact<Required/><select className={input} name="preferred_contact" required defaultValue="email"><option value="email">Email</option><option value="phone">Phone</option></select></label>
    <div className="mt-4 border-t border-cream/15 pt-7 md:col-span-2"><h2 className="font-display text-3xl">Public property information</h2><p className="mt-2 text-sm text-ink/60">Use a town or general area only. Do not enter the property’s street address.</p></div>
    <label className="text-sm font-bold">Property name<Required/><input className={input} name="property_name" required maxLength={140}/></label>
    <label className="text-sm font-bold">General location<Required/><select className={input} name="location" required><option>Heber</option><option>Overgaard</option><option>Forest Lakes</option><option>Nearby area</option></select></label>
    <label className="text-sm font-bold">Neighborhood or general-area description<input className={input} name="general_area" maxLength={160} placeholder="Optional — no street address"/></label>
    <label className="text-sm font-bold">Property type<Required/><select className={input} name="property_type" required><option>Cabin</option><option>House</option><option>Condo</option><option>Guesthouse</option><option>Other</option></select></label>
    <fieldset className="grid gap-5 border border-red-400/35 p-4 md:col-span-2 md:grid-cols-2"><legend className="px-2 text-sm font-bold">Booking links<Required/> <span className="font-normal text-red-400">Provide at least one</span></legend><label className="text-sm font-bold">Airbnb URL<input className={input} name="airbnb_url" type="url" maxLength={500} placeholder="https://www.airbnb.com/…"/></label><label className="text-sm font-bold">Vrbo URL<input className={input} name="vrbo_url" type="url" maxLength={500} placeholder="https://www.vrbo.com/…"/></label><label className="text-sm font-bold md:col-span-2">Direct-booking URL<input className={input} name="direct_booking_url" type="url" maxLength={500} placeholder="https://your-booking-site.com/…"/></label></fieldset>
    <label className="text-sm font-bold">Maximum guests<Required/><input className={input} name="max_guests" type="number" min={1} max={100} required/></label>
    <div className="grid grid-cols-2 gap-4"><label className="text-sm font-bold">Bedrooms<Required/><input className={input} name="bedrooms" type="number" min={0} max={50} step="0.5" required/></label><label className="text-sm font-bold">Bathrooms<Required/><input className={input} name="bathrooms" type="number" min={0} max={50} step="0.5" required/></label></div>
    <fieldset className="border border-forest/20 p-4 md:col-span-2"><legend className="px-2 text-sm font-bold">Pet friendly?</legend><div className="flex gap-6"><label><input type="radio" name="pet_friendly" value="yes"/> Yes</label><label><input type="radio" name="pet_friendly" value="no" defaultChecked/> No</label></div></fieldset>
    <label className="text-sm font-bold md:col-span-2">Short description<Required/> <span className="font-normal">(220 characters)</span><textarea className="mt-2 w-full border border-cream/20 p-3 font-normal" name="short_description" required maxLength={220} rows={3}/></label>
    <label className="text-sm font-bold md:col-span-2">Full property description<Required/> <span className="font-normal">(4,000 characters)</span><textarea className="mt-2 w-full border border-cream/20 p-3 font-normal" name="description" required maxLength={4000} rows={8}/></label>
    <label className="text-sm font-bold">Amenities<textarea className="mt-2 w-full border border-cream/20 p-3 font-normal" name="amenities" maxLength={1500} rows={6} placeholder="One per line or comma-separated"/></label>
    <label className="text-sm font-bold">Property highlights<textarea className="mt-2 w-full border border-cream/20 p-3 font-normal" name="highlights" maxLength={1500} rows={6} placeholder="One per line or comma-separated"/></label>
    <div className="md:col-span-2"><label className="text-sm font-bold">Photos<Required/> <span className="font-normal">(1–10 JPG, PNG, or WebP; 5 MB each)</span><input className={input} type="file" accept="image/jpeg,image/png,image/webp" required multiple onChange={event=>{const next=Array.from(event.target.files||[]).slice(0,10);setFiles(next);setFeatured(0)}}/></label>{previews.length>0&&<fieldset className="mt-4"><legend className="text-sm font-bold">Choose the featured image</legend><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-5">{previews.map((item,index)=><label className={`border-2 p-2 ${featured===index?"border-sand":"border-transparent"}`} key={`${item.file.name}-${index}`}><img src={item.url} alt="Selected rental preview" className="aspect-[4/3] w-full object-cover"/><span className="mt-2 flex items-center gap-2 text-xs"><input type="radio" checked={featured===index} onChange={()=>setFeatured(index)}/> Featured</span></label>)}</div></fieldset>}</div>
    <section className="border border-sand/40 bg-sand/10 p-5 md:col-span-2"><h2 className="font-display text-2xl">Required acknowledgements<Required/></h2><p className="mt-2 text-sm font-bold text-red-400">Every acknowledgement below must be checked.</p><div className="mt-4 grid gap-3">{checks.map(([name,label])=><label className="flex items-start gap-3 text-sm leading-6" key={name}><input className="mt-1 size-5 shrink-0" type="checkbox" name={name} value="yes" required/><span>{label}</span></label>)}<label className="flex items-start gap-3 text-sm leading-6"><input className="mt-1 size-5 shrink-0" type="checkbox" name="terms_accepted" value="yes" required/><span>I accept the current <Link className="font-bold text-forest underline" target="_blank" href="/advertising-terms">Advertising Terms/Agreement</Link>. A complete copy will be emailed after successful payment.</span></label></div></section>
    <div className="md:col-span-2"><div className="mb-4 bg-forest/10 p-4"><strong>Due for this property: ${(priceCents/100).toFixed(2)} for one year.</strong><p className="mt-1 text-sm">Each property requires a separate submission and purchase. Payment places the listing into review; it does not publish it.</p></div><button disabled={state==="sending"||files.length<1||files.length>10} className="min-h-13 bg-pine px-7 py-4 font-bold text-cream disabled:opacity-50">{state==="sending"?"Saving and preparing checkout…":`Continue to secure payment — $${(priceCents/100).toFixed(2)}`}</button>{state==="error"&&<p role="alert" className="mt-3 font-bold text-red-400">{error}</p>}</div>
  </form>;
}
