import type {Business} from "@/types";
import {businesses as fallbackBusinesses} from "@/lib/data";
import {getSupabase} from "@/lib/supabase/server";
import {cleanOptional,validLatitude,validLongitude} from "@/lib/listings";

type HoursData={display?:string;source?:string;verified_at?:string};
type BusinessRow={id:string;name:string;slug:string;category:string|null;short_description:string|null;description:string|null;address:string|null;phone:string|null;email:string|null;website:string|null;image_url:string|null;latitude:number|string|null;longitude:number|string|null;location_type:"physical"|"service_area"|"online"|null;lodging_type:string|null;hours_json:HoursData|null;displaying_qr_sign:boolean|null;featured:boolean|null;sponsored:boolean|null;active:boolean|null};
export function rowToBusiness(row:BusinessRow):Business{const hours=row.hours_json||{};return {id:row.id,name:row.name,slug:row.slug,category:cleanOptional(row.category)||"Other",shortDescription:cleanOptional(row.short_description)||"",description:cleanOptional(row.description)||cleanOptional(row.short_description)||"",address:cleanOptional(row.address)||"",phone:cleanOptional(row.phone)||"",email:cleanOptional(row.email),website:cleanOptional(row.website)||"",image:cleanOptional(row.image_url)||"",latitude:validLatitude(row.latitude),longitude:validLongitude(row.longitude),locationType:row.location_type||"physical",lodgingType:cleanOptional(row.lodging_type),hours:cleanOptional(hours.display)?.replace(/\\n/g,"\n"),hoursSource:cleanOptional(hours.source),hoursVerifiedAt:cleanOptional(hours.verified_at),displayingQrSign:!!row.displaying_qr_sign,featured:!!row.featured,sponsored:!!row.sponsored,active:row.active!==false}}
const fields="id,name,slug,category,short_description,description,address,phone,email,website,image_url,latitude,longitude,location_type,lodging_type,hours_json,displaying_qr_sign,featured,sponsored,active";
export async function getBusinesses(options:{includeInactive?:boolean}={}):Promise<Business[]>{const db=await getSupabase();if(!db)return fallbackBusinesses;let query=db.from("businesses").select(fields).order("name");if(!options.includeInactive)query=query.eq("active",true);const {data,error}=await query;if(error){console.error("Unable to load Supabase businesses",error.message);return fallbackBusinesses}return (data as unknown as BusinessRow[]).map(rowToBusiness)}
export async function getBusiness(slug:string):Promise<Business|undefined>{const db=await getSupabase();if(!db)return fallbackBusinesses.find(x=>x.slug===slug);const {data,error}=await db.from("businesses").select(fields).eq("slug",slug).eq("active",true).maybeSingle();if(error){console.error("Unable to load Supabase business",error.message);return fallbackBusinesses.find(x=>x.slug===slug)}return data?rowToBusiness(data as unknown as BusinessRow):undefined}
export function businessToRow(b:Business){return {name:b.name,slug:b.slug,category:b.category,short_description:b.shortDescription,description:b.description,address:cleanOptional(b.address)||null,phone:cleanOptional(b.phone)||null,email:cleanOptional(b.email)||null,website:cleanOptional(b.website)||null,image_url:cleanOptional(b.image)||null,latitude:b.latitude||null,longitude:b.longitude||null,location_type:b.locationType||"physical",lodging_type:cleanOptional(b.lodgingType)||null,hours_json:{display:b.hours||"",source:b.hoursSource||"",verified_at:b.hoursVerifiedAt||""},displaying_qr_sign:!!b.displayingQrSign,featured:false,sponsored:false,active:b.active!==false}}
