import type {Business} from "@/types";
import {businesses as fallbackBusinesses} from "@/lib/data";
import {getSupabase} from "@/lib/supabase/server";

type BusinessRow={id:string;name:string;slug:string;category:string|null;short_description:string|null;description:string|null;address:string|null;phone:string|null;website:string|null;image_url:string|null;featured:boolean|null;sponsored:boolean|null;active:boolean|null};
export function rowToBusiness(row:BusinessRow):Business{return {id:row.id,name:row.name,slug:row.slug,category:row.category||"Other",shortDescription:row.short_description||"",description:row.description||row.short_description||"",address:row.address||"",phone:row.phone||"",website:row.website||"",image:row.image_url||"",featured:!!row.featured,sponsored:!!row.sponsored,active:row.active!==false}}
export async function getBusinesses(options:{includeInactive?:boolean}={}):Promise<Business[]>{const db=await getSupabase();if(!db)return fallbackBusinesses;let query=db.from("businesses").select("id,name,slug,category,short_description,description,address,phone,website,image_url,featured,sponsored,active").order("name");if(!options.includeInactive)query=query.eq("active",true);const {data,error}=await query;if(error){console.error("Unable to load Supabase businesses",error.message);return fallbackBusinesses}return (data as BusinessRow[]).map(rowToBusiness)}
export async function getBusiness(slug:string):Promise<Business|undefined>{const db=await getSupabase();if(!db)return fallbackBusinesses.find(x=>x.slug===slug);const {data,error}=await db.from("businesses").select("id,name,slug,category,short_description,description,address,phone,website,image_url,featured,sponsored,active").eq("slug",slug).eq("active",true).maybeSingle();if(error){console.error("Unable to load Supabase business",error.message);return fallbackBusinesses.find(x=>x.slug===slug)}return data?rowToBusiness(data as BusinessRow):undefined}
export function businessToRow(b:Business){return {name:b.name,slug:b.slug,category:b.category,short_description:b.shortDescription,description:b.description,address:b.address,phone:b.phone,website:b.website,image_url:b.image||null,featured:false,sponsored:false,active:b.active!==false}}
