import type {Attraction,Business,Deal,Event,Trail} from "@/types";
const img=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;
export const businesses:Business[]=[
{id:"b1",name:"Pine Ridge Coffee — DEMO",slug:"pine-ridge-coffee",category:"Coffee",shortDescription:"Small-batch coffee and mountain mornings.",description:"A demonstration listing showing how a local coffee shop profile can look. Details have not been verified.",address:"Demo address, Heber-Overgaard, AZ",phone:"(928) 555-0101",website:"#",image:img("photo-1445116572660-236099ec97a0"),featured:true,sponsored:true},
{id:"b2",name:"Rim Country Grill — DEMO",slug:"rim-country-grill",category:"Restaurants",shortDescription:"Comfort food inspired by Arizona's high country.",description:"Demonstration restaurant listing. Replace this content with verified business information.",address:"Demo address, Heber-Overgaard, AZ",phone:"(928) 555-0102",website:"#",image:img("photo-1414235077428-338989a2e8c0"),featured:true},
{id:"b3",name:"Mountain Mercantile — DEMO",slug:"mountain-mercantile",category:"Shopping",shortDescription:"Gifts, trail goods, and locally inspired finds.",description:"Demonstration retail listing.",address:"Demo address, Heber-Overgaard, AZ",phone:"(928) 555-0103",website:"#",image:img("photo-1441986300917-64674bd600d8")},
{id:"b4",name:"High Country Cabins — DEMO",slug:"high-country-cabins",category:"Lodging",shortDescription:"A cozy basecamp beneath the pines.",description:"Demonstration lodging listing.",address:"Demo address, Heber-Overgaard, AZ",phone:"(928) 555-0104",website:"#",image:img("photo-1449158743715-0a90ebb6d2d8"),featured:true},
{id:"b5",name:"Rimside Outfitters — DEMO",slug:"rimside-outfitters",category:"Outdoor & Adventure",shortDescription:"Gear up for a day outside.",description:"Demonstration outfitter listing.",address:"Demo address, Heber-Overgaard, AZ",phone:"(928) 555-0105",website:"#",image:img("photo-1551632811-561732d1e306")},
{id:"b6",name:"Juniper Bakery — DEMO",slug:"juniper-bakery",category:"Restaurants",shortDescription:"Fresh pastries and friendly faces.",description:"Demonstration bakery listing.",address:"Demo address, Heber-Overgaard, AZ",phone:"(928) 555-0106",website:"#",image:img("photo-1509440159596-0249088772ff")},
{id:"b7",name:"Ponderosa Realty — DEMO",slug:"ponderosa-realty",category:"Real Estate",shortDescription:"Local knowledge for high-country homes.",description:"Demonstration real estate listing.",address:"Demo address, Heber-Overgaard, AZ",phone:"(928) 555-0107",website:"#",image:img("photo-1560518883-ce09059eeffa")},
{id:"b8",name:"Blue Sky Market — DEMO",slug:"blue-sky-market",category:"Shopping",shortDescription:"Everyday essentials for your stay.",description:"Demonstration market listing.",address:"Demo address, Heber-Overgaard, AZ",phone:"(928) 555-0108",website:"#",image:img("photo-1578916171728-46686eac8d58")},
{id:"b9",name:"Forest Auto Care — DEMO",slug:"forest-auto-care",category:"Automotive",shortDescription:"Friendly help when the road gets rough.",description:"Demonstration automotive listing.",address:"Demo address, Heber-Overgaard, AZ",phone:"(928) 555-0109",website:"#",image:img("photo-1487754180451-c456f719a1fc")},
{id:"b10",name:"Rim Country Services — DEMO",slug:"rim-country-services",category:"Home Services",shortDescription:"Helping cabins and homes run smoothly.",description:"Demonstration services listing.",address:"Demo address, Heber-Overgaard, AZ",phone:"(928) 555-0110",website:"#",image:img("photo-1450101499163-c8848c66ca85")}
];
export const attractions:Attraction[]=[
{id:"a1",name:"Ponderosa Picnic Day — DEMO",slug:"ponderosa-picnic",category:"Parks",description:"A demo idea for an easy family picnic beneath tall pines.",image:img("photo-1500530855697-b586d89ba3ee"),costType:"Free",featured:true},
{id:"a2",name:"Rim View Scenic Stop — DEMO",slug:"rim-view",category:"Scenic",description:"A placeholder scenic experience. Verify access and conditions before visiting.",image:img("photo-1501785888041-af3ef285b470"),costType:"Free",featured:true},
{id:"a3",name:"High Country History Walk — DEMO",slug:"history-walk",category:"Historic",description:"A self-guided demo concept celebrating local history.",image:img("photo-1529107386315-e1a2ed48a620"),costType:"Free"},
{id:"a4",name:"Forest Discovery Loop — DEMO",slug:"forest-discovery",category:"Family Activities",description:"A demo family nature activity in the forest.",image:img("photo-1441974231531-c6227db76b6e"),costType:"Free"},
{id:"a5",name:"Mountain Lake Morning — DEMO",slug:"lake-morning",category:"Lakes",description:"A sample listing for a quiet morning by the water.",image:img("photo-1439853949127-fa647821eba0"),costType:"Varies"},
{id:"a6",name:"Wildlife Watch — DEMO",slug:"wildlife-watch",category:"Free",description:"Observe from a distance and leave wildlife wild.",image:img("photo-1484406566174-9da000fda645"),costType:"Free"},
{id:"a7",name:"Community Arts Stop — DEMO",slug:"arts-stop",category:"Museums",description:"Placeholder for a verified arts or cultural attraction.",image:img("photo-1564399579883-451a5d44ec08"),costType:"Varies"},
{id:"a8",name:"Stargazing Night — DEMO",slug:"stargazing",category:"Recreation",description:"A demo reminder to step outside and enjoy the dark sky.",image:img("photo-1419242902214-272b3f66ee7a"),costType:"Free"}
];
export const trails:Trail[]=[
{id:"t1",name:"Pine Needle Loop — DEMO",slug:"pine-needle-loop",description:"A gentle demo route among ponderosa pines.",distance:"1.8 mi",difficulty:"Easy",duration:"45 min",activityType:"Hiking",familyFriendly:true,image:img("photo-1551632811-561732d1e306")},
{id:"t2",name:"Rim Vista Trail — DEMO",slug:"rim-vista",description:"A sample route with expansive high-country views.",distance:"4.2 mi",difficulty:"Moderate",duration:"2 hr",activityType:"Scenic",familyFriendly:false,image:img("photo-1464822759023-fed622ff2c3b")},
{id:"t3",name:"Juniper Family Path — DEMO",slug:"juniper-family",description:"An approachable demo family walk.",distance:"0.9 mi",difficulty:"Easy",duration:"30 min",activityType:"Hiking",familyFriendly:true,image:img("photo-1500534314209-a25ddb2bd429")},
{id:"t4",name:"Canyon Climb — DEMO",slug:"canyon-climb",description:"A challenging demo route for prepared hikers.",distance:"7.1 mi",difficulty:"Difficult",duration:"4 hr",activityType:"Hiking",familyFriendly:false,image:img("photo-1464278533981-50106e6176b1")},
{id:"t5",name:"Lake Angler Access — DEMO",slug:"lake-angler",description:"A placeholder fishing-access listing.",distance:"0.5 mi",difficulty:"Easy",duration:"20 min",activityType:"Fishing",familyFriendly:true,image:img("photo-1500534623283-312aade485b7")},
{id:"t6",name:"High Country Ride — DEMO",slug:"high-country-ride",description:"A demonstration ATV route; verify legal access before use.",distance:"12 mi",difficulty:"Moderate",duration:"3 hr",activityType:"ATV",familyFriendly:false,image:img("photo-1501554728187-ce583db33af7")}
];
export const events:Event[]=[1,2,3,4,5].map((n)=>({id:`e${n}`,name:["Pinecone Market","Mountain Music Evening","Family Nature Hour","High Country Art Walk","Community Campfire"][n-1]+" — DEMO",slug:`demo-event-${n}`,description:"Sample event content. Confirm dates and details with the organizer.",startDate:new Date(Date.now()+n*86400000*7).toISOString(),time:n%2?"10:00 AM":"6:00 PM",location:"Demo venue, Heber-Overgaard",category:n%2?"Community":"Arts",image:img(["photo-1488459716781-31db52582fe9","photo-1492684223066-81342ee5ff30","photo-1472396961693-142e6e269027","photo-1549490349-8643362247b5","photo-1475483768296-6163e08872a1"][n-1])}));
export const deals:Deal[]=[1,2,3,4,5].map((n)=>({id:`d${n}`,businessId:`b${n}`,title:["Trail-Day Coffee","Local Lunch Special","Visitor Gift","Two-Night Escape","Gear-Up Bonus"][n-1]+" — DEMO",description:"A sample visitor offer for demonstrating local deals.",code:`RIM${n}0`,expirationDate:"2027-12-31",terms:"Demo only. Not a valid offer.",featured:n<3}));
export const categories=["Things To Do","Eat & Drink","Free Things","Trails","Events","Shop Local","Places To Stay","Local Deals"];
