import type {Attraction,Business,Deal,Event,Trail} from "@/types";
const img=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;
export const businesses:Business[]=[
{id:"b1",name:"Aztec Coffee & Taproom",slug:"aztec-coffee-taproom",category:"Coffee",shortDescription:"Coffee and taproom at Bison Ranch.",description:"A local coffee and taproom at Bison Ranch. Check the business website for current hours and offerings.",address:"2377 Bison Ranch Trail #113, Overgaard, AZ 85933",phone:"(928) 940-9309",website:"https://www.aztexaz.com/",image:img("photo-1445116572660-236099ec97a0"),featured:true},
{id:"b2",name:"The Red Onion Bar & Grill",slug:"red-onion-bar-grill",category:"Restaurants",shortDescription:"Burgers, steaks, hand-cut fries, and hometown hospitality.",description:"A family-friendly Heber-Overgaard restaurant established in 1994, known for burgers, steaks, hand-cut fries, weekly specials, and a dog-friendly patio.",address:"1931 State Highway 260, Overgaard, AZ 85933",phone:"(928) 535-4433",website:"https://www.redoniononline.com/",image:"/images/town/red-onion-interior.jpg",featured:true},
{id:"b3",name:"Sanders Coffee & Co",slug:"sanders-coffee-co",category:"Coffee",shortDescription:"Locally owned coffee shop in Heber.",description:"A locally owned coffee shop serving the Heber-Overgaard community. Verify current hours and menu directly before visiting.",address:"1900 State Route 260, Heber, AZ 85928",phone:"(623) 986-8395",website:"https://www.facebook.com/sanderscoffeeandco/",image:"/images/town/sanders-storefront.jpg",featured:true},
{id:"b4",name:"Best Western Sawmill Inn",slug:"best-western-sawmill-inn",category:"Lodging",shortDescription:"High-country lodging with Wi-Fi and EV charging.",description:"A hotel in Heber listed by the local Chamber, offering visitor lodging and amenities. Confirm rates and availability directly.",address:"1877 State Route 260, Heber, AZ 85928",phone:"(928) 535-5053",website:"https://www.bestwestern.com/",image:img("photo-1449158743715-0a90ebb6d2d8"),featured:true},
{id:"b5",name:"D & M Outfitters",slug:"d-m-outfitters",category:"Outdoor & Adventure",shortDescription:"Hunting, fishing, outdoor supplies, and gunsmithing.",description:"A local outfitter offering outdoor recreation supplies, including hunting and fishing gear and gunsmithing services.",address:"3410 Buckskin Canyon Rd Ste 1, Heber, AZ 85928",phone:"(480) 640-9490",website:"https://heberovergaard.org/member-directory/",image:img("photo-1551632811-561732d1e306")},
{id:"b6",name:"June's Cafe",slug:"junes-cafe",category:"Restaurants",shortDescription:"Family-style restaurant in Heber.",description:"A family-style restaurant listed in the current Heber-Overgaard Chamber directory. Confirm current hours directly.",address:"1990 State Route 260, Heber, AZ 85928",phone:"(928) 535-4510",website:"https://heberovergaard.org/member-directory/",image:img("photo-1552566626-52f8b828add9")},
{id:"b7",name:"Ponderosa Cafe",slug:"ponderosa-cafe",category:"Restaurants",shortDescription:"Family comfort food in the heart of the community.",description:"A multi-generation, family-owned and operated restaurant serving familiar comfort food in Heber-Overgaard.",address:"2935 State Route 260, Overgaard, AZ 85933",phone:"(928) 240-1706",website:"https://ponderosacafeaz.com/",image:img("photo-1515003197210-e0cd71810b5f")},
{id:"b8",name:"Pit Stop Pizza",slug:"pit-stop-pizza",category:"Restaurants",shortDescription:"Handcrafted pizza, wings, calzones, salads, and an arcade.",description:"A family-friendly local pizza restaurant serving Heber-Overgaard for more than 20 years, with pizza, wings, calzones, salads, desserts, and an arcade.",address:"2232 State Route 260, Overgaard, AZ 85933",phone:"(928) 535-5711",website:"https://www.pitstoppizzaaz.com/",image:img("photo-1579751626657-72bc17010498")},
{id:"b9",name:"KL's Asian Kitchen",slug:"kls-asian-kitchen",category:"Restaurants",shortDescription:"Asian cuisine on State Route 260 in Heber.",description:"A local Asian restaurant listed by the Heber-Overgaard Chamber. Check the official website for current menu and hours.",address:"1945 State Route 260, Heber, AZ 85928",phone:"(480) 535-8008",website:"https://www.klskitchen.com/",image:img("photo-1525755662778-989d0524087e")},
{id:"b10",name:"AJ's Getaway RV Park",slug:"ajs-getaway-rv-park",category:"Lodging",shortDescription:"RV stays among the pines in Overgaard.",description:"An RV park in Overgaard listed by the local Chamber. Confirm availability, site details, and seasonal information directly.",address:"3537 Buckskin Rd, Overgaard, AZ 85933",phone:"(928) 433-8060",website:"https://www.ajsgetawayrv.com/",image:img("photo-1532339142463-fd0a8979791a")}
];
export const attractions:Attraction[]=[
{id:"a1",name:"Tall Timbers Park",slug:"tall-timbers-park",category:"Parks",description:"A public Navajo County park in Heber-Overgaard and a community gathering place. Check current access and event use before visiting.",image:img("photo-1500530855697-b586d89ba3ee"),costType:"Free",featured:true},
{id:"a2",name:"Mogollon Rim",slug:"mogollon-rim",category:"Scenic",description:"A dramatic forested escarpment with broad viewpoints, scenic drives, trails, and seasonal recreation access.",image:"/images/town/winter-rim.jpg",costType:"Free",featured:true},
{id:"a3",name:"Rock House Museum",slug:"rock-house-museum",category:"Historic",description:"A local-history stop highlighted by the Heber-Overgaard Chamber. Verify opening dates and hours before visiting.",image:img("photo-1529107386315-e1a2ed48a620"),costType:"Varies"},
{id:"a4",name:"Rim Community Library",slug:"rim-community-library",category:"Family Activities",description:"Community library providing access to information, a community room, and a welcoming indoor stop.",image:img("photo-1521587760476-6c12a4b040da"),costType:"Free"},
{id:"a5",name:"Woods Canyon Lake",slug:"woods-canyon-lake",category:"Lakes",description:"A popular Mogollon Rim lake recreation area for fishing, picnicking, camping, and access to nearby trails. Seasonal roads and fees may apply.",image:img("photo-1439853949127-fa647821eba0"),costType:"Varies"},
{id:"a6",name:"Willow Springs Lake",slug:"willow-springs-lake",category:"Lakes",description:"A forest lake along the Rim corridor used for fishing and outdoor recreation. Check current Forest Service conditions.",image:img("photo-1500534623283-312aade485b7"),costType:"Varies"},
{id:"a7",name:"Black Canyon Lake",slug:"black-canyon-lake",category:"Lakes",description:"A Black Mesa Ranger District lake south of Heber-Overgaard. Access can be seasonal; check alerts and road conditions.",image:img("photo-1470252649378-9c29740c9fa8"),costType:"Varies"},
{id:"a8",name:"Apache-Sitgreaves National Forests",slug:"apache-sitgreaves",category:"Recreation",description:"The surrounding national forest offers hiking, fishing, camping, scenic viewing, wildlife watching, and winter recreation.",image:"/images/town/ponderosa-forest.jpg",costType:"Free"}
];
export const trails:Trail[]=[
{id:"t1",name:"Rim Vista Trail",slug:"rim-vista-trail",description:"A paved, accessible Rim trail connecting scenic overlooks, campground areas, and Woods Canyon Lake recreation facilities.",distance:"3+ mi",difficulty:"Easy",duration:"1–2 hr",activityType:"Scenic",familyFriendly:true,image:img("photo-1551632811-561732d1e306")},
{id:"t2",name:"235 Road Trail",slug:"235-road-trail",description:"A non-motorized trail in a designated wildlife habitat area, used for hiking, horseback riding, and mountain biking.",distance:"Verify locally",difficulty:"Moderate",duration:"Varies",activityType:"Hiking",familyFriendly:false,image:img("photo-1464822759023-fed622ff2c3b")},
{id:"t3",name:"237 B OHV Trail",slug:"237-b-ohv-trail",description:"A short Forest Service OHV connector from the 237 B Trailhead to Larson Canyon Trail for vehicles up to 68 inches wide.",distance:"0.5 mi",difficulty:"Moderate",duration:"Varies",activityType:"ATV",familyFriendly:false,image:img("photo-1500534314209-a25ddb2bd429")},
{id:"t4",name:"99a OHV Trail",slug:"99a-ohv-trail",description:"An ATV route beginning at Wildcat Road Access in Forest Lakes and ending at Forest Road 172.",distance:"3.9 mi",difficulty:"Moderate",duration:"Varies",activityType:"ATV",familyFriendly:false,image:img("photo-1501554728187-ce583db33af7")},
{id:"t5",name:"Woods Canyon Lake Trail",slug:"woods-canyon-lake-trail",description:"A lake-area walking route through ponderosa forest. Confirm the current official route, access, and seasonal conditions before setting out.",distance:"Verify locally",difficulty:"Easy",duration:"Varies",activityType:"Hiking",familyFriendly:true,image:img("photo-1500534623283-312aade485b7")},
{id:"t6",name:"Mogollon Rim Trail Corridor",slug:"mogollon-rim-trail-corridor",description:"A scenic high-country trail corridor with multiple access points and changing conditions. Use an official Forest Service map for route planning.",distance:"Varies",difficulty:"Moderate",duration:"Varies",activityType:"Scenic",familyFriendly:false,image:img("photo-1464278533981-50106e6176b1")}
];
export const events:Event[]=[1,2,3,4,5].map((n)=>({id:`e${n}`,name:["Pinecone Market","Mountain Music Evening","Family Nature Hour","High Country Art Walk","Community Campfire"][n-1]+" — DEMO",slug:`demo-event-${n}`,description:"Sample event content. Confirm dates and details with the organizer.",startDate:new Date(Date.now()+n*86400000*7).toISOString(),time:n%2?"10:00 AM":"6:00 PM",location:"Demo venue, Heber-Overgaard",category:n%2?"Community":"Arts",image:img(["photo-1488459716781-31db52582fe9","photo-1492684223066-81342ee5ff30","photo-1472396961693-142e6e269027","photo-1549490349-8643362247b5","photo-1475483768296-6163e08872a1"][n-1])}));
export const deals:Deal[]=[];
export const categories=["Things To Do","Eat & Drink","Free Things","Trails","Events","Shop Local","Places To Stay","Local Deals"];
