import type {Attraction,Business,Deal,Event,Trail} from "@/types";
const img=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;
export const businesses:Business[]=[
{id:"b1",name:"Aztec Coffee & Taproom",slug:"aztec-coffee-taproom",category:"Coffee",shortDescription:"Coffee and taproom at Bison Ranch.",description:"A local coffee and taproom at Bison Ranch. Check the business website for current hours and offerings.",address:"2377 Bison Ranch Trail #113, Overgaard, AZ 85933",phone:"(928) 940-9309",website:"https://www.aztexaz.com/",image:img("photo-1445116572660-236099ec97a0"),featured:true},
{id:"b2",name:"The Red Onion Bar & Grill",slug:"red-onion-bar-grill",category:"Restaurants",shortDescription:"Burgers, steaks, hand-cut fries, and hometown hospitality.",description:"A family-friendly Heber-Overgaard restaurant established in 1994, known for burgers, steaks, hand-cut fries, weekly specials, and a dog-friendly patio.",address:"1931 State Highway 260, Overgaard, AZ 85933",phone:"(928) 535-4433",website:"https://www.redoniononline.com/",image:"/images/town/red-onion-interior.jpg",featured:true},
{id:"b3",name:"Sanders Coffee & Co",slug:"sanders-coffee-co",category:"Coffee",shortDescription:"Locally owned coffee shop in Heber.",description:"A locally owned coffee shop serving the Heber-Overgaard community. Verify current hours and menu directly before visiting.",address:"1900 State Route 260, Heber, AZ 85928",phone:"(623) 986-8395",website:"https://www.facebook.com/sanderscoffeeandco/",image:"/images/town/sanders-storefront.jpg",featured:true},
{id:"b4",name:"Best Western Sawmill Inn",slug:"best-western-sawmill-inn",category:"Lodging",shortDescription:"High-country lodging with Wi-Fi and EV charging.",description:"A hotel in Heber listed by the local Chamber, offering visitor lodging and amenities. Confirm rates and availability directly.",address:"1877 State Route 260, Heber, AZ 85928",phone:"(928) 535-5053",website:"https://www.bestwestern.com/",image:img("photo-1449158743715-0a90ebb6d2d8"),featured:true},
{id:"b5",name:"D & M Outfitters",slug:"d-m-outfitters",category:"Outdoor & Adventure",shortDescription:"Hunting, fishing, outdoor supplies, and gunsmithing.",description:"A local outfitter offering outdoor recreation supplies, including hunting and fishing gear and gunsmithing services.",address:"3410 Buckskin Canyon Rd Ste 1, Heber, AZ 85928",phone:"(480) 640-9490",website:"https://heberovergaard.org/member-directory/",image:img("photo-1551632811-561732d1e306")},
{id:"b6",name:"June's Cafe",slug:"junes-cafe",category:"Restaurants",shortDescription:"Family-style restaurant in Heber.",description:"A family-style restaurant listed in the current Heber-Overgaard Chamber directory. Confirm current hours directly.",address:"1990 State Route 260, Heber, AZ 85928",phone:"(928) 535-4510",website:"https://heberovergaard.org/member-directory/",image:img("photo-1552566626-52f8b828add9")},
{id:"b7",name:"Ponderosa Cafe",slug:"ponderosa-cafe",category:"Restaurants",shortDescription:"Family comfort food in the heart of the community.",description:"A multi-generation, family-owned and operated restaurant serving familiar comfort food in Heber-Overgaard.",address:"2935 State Route 260, Overgaard, AZ 85933",phone:"(928) 240-1706",website:"https://ponderosacafeaz.com/",image:img("photo-1515003197210-e0cd71810b5f")},
{id:"b8",name:"Pit Stop Pizza",slug:"pit-stop-pizza",category:"Restaurants",shortDescription:"Handcrafted pizza, wings, calzones, salads, and an arcade.",description:"A family-friendly local pizza restaurant serving Heber-Overgaard for more than 20 years, with pizza, wings, calzones, salads, desserts, and an arcade.",address:"2232 State Route 260, Overgaard, AZ 85933",phone:"(928) 535-5711",website:"https://www.pitstoppizzaaz.com/",image:img("photo-1579751626657-72bc17010498")},
{id:"b9",name:"KL's Asian Kitchen",slug:"kls-asian-kitchen",category:"Restaurants",shortDescription:"Asian cuisine on State Route 260 in Heber.",description:"A local Asian restaurant listed by the Heber-Overgaard Chamber. Check the official website for current menu and hours.",address:"1945 State Route 260, Heber, AZ 85928",phone:"(480) 535-8008",website:"https://www.klskitchen.com/",image:img("photo-1525755662778-989d0524087e")},
{id:"b10",name:"AJ's Getaway RV Park",slug:"ajs-getaway-rv-park",category:"Lodging",shortDescription:"RV stays among the pines in Overgaard.",description:"An RV park in Overgaard listed by the local Chamber. Confirm availability, site details, and seasonal information directly.",address:"3537 Buckskin Rd, Overgaard, AZ 85933",phone:"(928) 433-8060",website:"https://www.ajsgetawayrv.com/",image:img("photo-1532339142463-fd0a8979791a")},
{id:"b11",name:"The Big Red Barn Marketplace",slug:"big-red-barn-marketplace",category:"Shopping",shortDescription:"Indoor marketplace with antiques, art, specialty shops, and local finds.",description:"An indoor marketplace with a mix of specialty shops, antiques, regional foods, clothing, original art, woodworking, and other local finds. Confirm current vendors and hours directly.",address:"3402 Kimball St, Heber, AZ 85928",phone:"(480) 560-6806",website:"https://heberovergaard.org/member-directory/",image:img("photo-1441986300917-64674bd600d8")},
{id:"b12",name:"Three Bear's Cafe",slug:"three-bears-cafe",category:"Restaurants",shortDescription:"Local cafe serving breakfast and lunch favorites.",description:"A local Heber cafe known for breakfast, lunch, and a friendly small-town atmosphere. Confirm the current menu and hours directly.",address:"1824 AZ-260, Heber, AZ 85928",phone:"(928) 535-6471",website:"https://www.facebook.com/threebearscafellc",image:img("photo-1552566626-52f8b828add9")},
{id:"b13",name:"Aliberto's Mexican Restaurant",slug:"alibertos-mexican-restaurant",category:"Restaurants",shortDescription:"Family-owned Mexican food with quick-service favorites.",description:"A family-owned Mexican restaurant serving traditional and quick-service favorites in Heber. Check the official site for current menu information.",address:"1835 AZ-260, Heber, AZ 85928",phone:"(928) 535-4007",website:"https://www.alibertos.com/",image:img("photo-1565299585323-38d6b0865b47")},
{id:"b14",name:"The Market at Heber",slug:"the-market-at-heber",category:"Shopping",shortDescription:"Local grocery store with produce, meat, pantry goods, and everyday supplies.",description:"Heber's local grocery market carries conventional, natural, gourmet, and locally sourced products along with produce, meat, and visitor essentials.",address:"1823 Black Canyon Dr, Heber, AZ 85928",phone:"(928) 535-3220",website:"https://mymarketstores.com/heber/",image:img("photo-1578916171728-46686eac8d58")},
{id:"b15",name:"Casa Ramos",slug:"casa-ramos",category:"Restaurants",shortDescription:"Mexican restaurant on State Route 260 in Heber.",description:"A local Mexican restaurant in Heber. Confirm current hours, menu, and ordering options directly before visiting.",address:"1855 AZ-260, Heber, AZ 85928",phone:"(928) 535-4448",website:"https://www.toasttab.com/local/casa-ramos-new-em-1855-hwy-260/r-573c2fcc-924d-4324-a8c6-cad0390b7288",image:img("photo-1541544741938-0af808871cc0")},
{id:"b16",name:"ACE Hardware",slug:"ace-hardware-overgaard",category:"Shopping",shortDescription:"Hardware, home, cabin, and outdoor supplies.",description:"A local hardware store serving residents and visitors in Overgaard. Confirm current inventory and hours directly.",address:"2837 AZ-260, Overgaard, AZ 85933",phone:"(928) 535-6335",website:"https://heberovergaard.org/member-directory/",image:img("photo-1581783898377-1c85bf937427")},
{id:"b17",name:"BaseCamp RV",slug:"basecamp-rv",category:"Lodging",shortDescription:"RV spaces and high-country stays in Overgaard.",description:"An Overgaard RV property listed by the local Chamber. Confirm rates, availability, amenities, and seasonal information directly.",address:"2162 Camperland Rd, Overgaard, AZ 85933",phone:"(928) 242-9851",website:"https://basecamprvaz.com/",image:img("photo-1532339142463-fd0a8979791a")},
{id:"b18",name:"Heber-Overgaard Chevron",slug:"heber-overgaard-chevron",category:"Automotive",shortDescription:"Fuel, convenience store, propane, ATM, beer, and wine.",description:"A local fuel and convenience stop offering gasoline, propane, an ATM, and travel essentials.",address:"1977 State Route 260, Overgaard, AZ 85933",phone:"(928) 535-5474",website:"https://www.chevron.com/",image:img("photo-1545262810-77515befe149")},
{id:"b19",name:"Christina's Woodshed Cafe",slug:"christinas-woodshed-cafe",category:"Restaurants",shortDescription:"Local cafe serving breakfast and lunch favorites.",description:"A longtime local cafe in Overgaard. Confirm current menu and operating hours directly before visiting.",address:"2232 AZ-260, Overgaard, AZ 85933",phone:"(928) 535-3700",website:"https://heberovergaard.org/member-directory/",image:img("photo-1552566626-52f8b828add9")},
{id:"b20",name:"Dairy Queen Grill & Chill",slug:"dairy-queen-heber-overgaard",category:"Restaurants",shortDescription:"Grill favorites, frozen treats, and specialty cakes.",description:"A local Dairy Queen Grill & Chill serving meals, frozen treats, and specialty cakes.",address:"1977 State Route 260, Overgaard, AZ 85933",phone:"(928) 535-5859",website:"https://www.dairyqueen.com/",image:img("photo-1563805042-7684c019e1cb")},
{id:"b21",name:"GiGi's Pizza",slug:"gigis-pizza",category:"Restaurants",shortDescription:"Pizza and casual family dining in Overgaard.",description:"A local pizza restaurant in Overgaard. Confirm the current menu, address details, and hours directly.",address:"2767 AZ-260, Overgaard, AZ 85933",phone:"(928) 535-4445",website:"https://heberovergaard.org/member-directory/",image:img("photo-1579751626657-72bc17010498")},
{id:"b22",name:"Gustava & Betty Soul Food",slug:"gustava-betty-soul-food",category:"Restaurants",shortDescription:"Authentic soul food in Heber-Overgaard.",description:"A local restaurant serving authentic soul food in Heber. Check the business website for current hours and menu.",address:"1882 State Route 260, Heber, AZ 85928",phone:"(480) 358-7782",website:"https://gustavaandbettysoulfood.com/",image:img("photo-1547592180-85f173990554")},
{id:"b23",name:"Junk Warehouse",slug:"junk-warehouse",category:"Shopping",shortDescription:"Thrift, antique, and collectible shopping.",description:"A local place to browse thrift items, antiques, and collectibles in Overgaard. Confirm current hours directly.",address:"2232 State Route 260, Overgaard, AZ 85933",phone:"(360) 888-9083",website:"https://heberovergaard.org/member-directory/",image:img("photo-1528698827591-e19ccd7bc23d")},
{id:"b24",name:"Miss Bo's Mercantile",slug:"miss-bos-mercantile",category:"Shopping",shortDescription:"Small-town retail at Bison Ranch.",description:"A local retail shop at Bison Ranch in Overgaard. Confirm current merchandise and hours directly.",address:"2377 Bison Ranch Trail #118, Overgaard, AZ 85933",phone:"(602) 549-3125",website:"https://heberovergaard.org/member-directory/",image:img("photo-1441986300917-64674bd600d8")},
{id:"b25",name:"Mogollon Family Dentistry",slug:"mogollon-family-dentistry",category:"Professional Services",shortDescription:"Local dental care in Overgaard.",description:"A dental practice serving the Heber-Overgaard community. Contact the office directly for appointments and services.",address:"3367 Buckskin Rd, Overgaard, AZ 85933",phone:"(928) 535-5886",website:"https://heberovergaard.org/member-directory/",image:img("photo-1609840114035-3c981b782dfe")},
{id:"b26",name:"Mountain Top Fitness",slug:"mountain-top-fitness",category:"Professional Services",shortDescription:"Local fitness facility in Overgaard.",description:"A local fitness facility serving residents and visitors. Confirm current access options, classes, and hours directly.",address:"2935 State Route 260, Overgaard, AZ 85933",phone:"(928) 535-4441",website:"https://heberovergaard.org/member-directory/",image:img("photo-1534438327276-14e5300c3a48")},
{id:"b27",name:"NAPA of Overgaard",slug:"napa-of-overgaard",category:"Automotive",shortDescription:"Auto parts, repairs, and 24-hour towing.",description:"A local NAPA Auto Parts store and repair facility offering automotive supplies, service, and towing.",address:"2828 State Route 260, Overgaard, AZ 85933",phone:"(928) 535-4898",website:"https://www.napaonline.com/",image:img("photo-1487754180451-c456f719a1fc")},
{id:"b28",name:"Overgaard RV Resort",slug:"overgaard-rv-resort",category:"Lodging",shortDescription:"RV accommodations in Overgaard.",description:"An RV resort in Overgaard. Contact the property directly for current availability, rates, amenities, and seasonal information.",address:"2750 Yates Rd, Overgaard, AZ 85933",phone:"(928) 535-4430",website:"https://heberovergaard.org/member-directory/",image:img("photo-1532339142463-fd0a8979791a")},
{id:"b29",name:"Packer's Print & Ship",slug:"packers-print-ship",category:"Professional Services",shortDescription:"Printing, copying, shipping, scanning, and document services.",description:"A local business offering printing, copying, laminating, binding, shredding, faxing, scanning, oversized prints, and photo services.",address:"2947 State Route 260 #1, Overgaard, AZ 85933",phone:"(928) 242-5283",website:"https://heberovergaard.org/member-directory/",image:img("photo-1562654501-a0ccc0fc3fb1")},
{id:"b30",name:"The Cabin Bar & Grill",slug:"the-cabin-bar-grill",category:"Restaurants",shortDescription:"Bar and grill on State Route 260 in Overgaard.",description:"A local bar and grill in Overgaard. Confirm current menu, age policies, events, and hours directly.",address:"2763 State Route 260, Overgaard, AZ 85933",phone:"(928) 535-4993",website:"https://heberovergaard.org/member-directory/",image:img("photo-1515003197210-e0cd71810b5f")},
{id:"b31",name:"Windy Hills Lavender Farm",slug:"windy-hills-lavender-farm",category:"Shopping",shortDescription:"Locally grown lavender and lavender-made goods.",description:"A boutique lavender farm growing multiple varieties and producing a range of lavender goods. Confirm visiting and shopping hours directly.",address:"3384 Stone Bridge Trail, Heber, AZ 85928",phone:"(928) 240-2273",website:"https://heberovergaard.org/member-directory/",image:img("photo-1499002238440-d264edd596ec")},
{id:"b32",name:"Woodchuck Saw and Cycle",slug:"woodchuck-saw-cycle",category:"Shopping",shortDescription:"Outdoor power equipment sales and repair.",description:"An authorized STIHL, Husqvarna, and ECHO dealer providing sales and repair for two- and four-cycle outdoor equipment.",address:"1846 State Route 260, Heber, AZ 85928",phone:"(928) 535-3144",website:"https://heberovergaard.org/member-directory/",image:img("photo-1530124566582-a618bc2615dc")},
{id:"b33",name:"260 Brewery & Distillery · Wild Women Saloon & Grill",slug:"260-brewery-wild-women-saloon",category:"Restaurants",shortDescription:"Brewery, distillery, saloon, and grill on Highway 260.",description:"A local brewery, distillery, saloon, and grill listed by the Heber-Overgaard Chamber. Confirm current hours and offerings directly.",address:"2279 Hwy 260, Overgaard, AZ 85933",phone:"(562) 233-1817",website:"https://heberovergaard.org/member-directory/",image:img("photo-1515003197210-e0cd71810b5f")},
{id:"b34",name:"Amore Rim Salon",slug:"amore-rim-salon",category:"Health & Wellness",shortDescription:"Full-service local beauty salon.",description:"A full-service beauty salon serving Heber-Overgaard. Contact the business directly for current services, appointments, and hours.",address:"1900 Hwy 260, Heber, AZ 85928",phone:"(928) 535-5422",website:"https://heberovergaard.org/member-directory/",image:img("photo-1560066984-138dadb4c035")},
{id:"b35",name:"Arizona Building Supply",slug:"arizona-building-supply",category:"Home Services",shortDescription:"Building materials and supplies in Heber.",description:"A local building-supply business serving residents, property owners, and contractors. Confirm current inventory and hours directly.",address:"2950 Hwy 260, Heber, AZ 85928",phone:"(928) 535-5356",website:"https://heberovergaard.org/member-directory/",image:img("photo-1504307651254-35680f356dfd")},
{id:"b36",name:"Bolt Adventures Transport & Containers",slug:"bolt-adventures-transport-containers",category:"Professional Services",shortDescription:"Transport and container services in Overgaard.",description:"A local transport and container-services business listed by the Heber-Overgaard Chamber. Contact the business for current services and availability.",address:"2849 SR 260, Overgaard, AZ 85933",phone:"(480) 400-0995",website:"https://heberovergaard.org/member-directory/",image:img("photo-1586528116311-ad8dd3c8310d")},
{id:"b37",name:"Bryce Computers",slug:"bryce-computers",category:"Professional Services",shortDescription:"Local computer and technology services.",description:"A local technology-services business serving the Heber-Overgaard community. Contact the business for current support options and hours.",address:"3401 Kimball St, Heber, AZ 85928",phone:"(928) 940-6090",website:"https://heberovergaard.org/member-directory/",image:img("photo-1516321318423-f06f85e504b3")},
{id:"b38",name:"Canyon Rim Dental Heber",slug:"canyon-rim-dental-heber",category:"Health & Wellness",shortDescription:"Local dental care focused on health and aesthetics.",description:"A Heber dental practice providing personalized dental care. Contact the office directly for services, appointments, and insurance information.",address:"3387 Sawmill Pointe Rd #369, Heber, AZ 85928",phone:"(928) 228-5446",website:"https://heberovergaard.org/member-directory/",image:img("photo-1609840114035-3c981b782dfe")},
{id:"b39",name:"Country Club Storage",slug:"country-club-storage",category:"Professional Services",shortDescription:"Storage services in Overgaard.",description:"A local storage business in Overgaard. Contact the business directly for unit availability, rates, access, and current office hours.",address:"2762 Mogollon Dr, Overgaard, AZ 85933",phone:"(928) 240-1700",website:"https://heberovergaard.org/member-directory/",image:img("photo-1590247813693-5541d1c609fd")},
{id:"b40",name:"Golden Soul Massage Studio",slug:"golden-soul-massage-studio",category:"Health & Wellness",shortDescription:"Massage studio at Bison Ranch.",description:"A local massage studio at Bison Ranch. Contact the business directly for current services, appointments, and hours.",address:"2377 Bison Ranch Trail #116, Overgaard, AZ 85933",phone:"(480) 283-7191",website:"https://heberovergaard.org/member-directory/",image:img("photo-1544161515-4ab6ce6db874")},
{id:"b41",name:"Heber RV Resort",slug:"heber-rv-resort",category:"Lodging",shortDescription:"RV spaces and high-country stays near Highway 277.",description:"An RV resort serving Heber-Overgaard visitors. Confirm current rates, availability, amenities, and seasonal information directly.",address:"3065 AZ Hwy 277, Overgaard, AZ 85933",phone:"(928) 535-4004",website:"https://heberovergaard.org/member-directory/",image:img("photo-1532339142463-fd0a8979791a")},
{id:"b42",name:"Lady Nay's Boutique",slug:"lady-nays-boutique",category:"Shopping",shortDescription:"Local boutique inside the Big Red Barn marketplace.",description:"A local boutique at the Big Red Barn marketplace. Confirm current merchandise and hours directly.",address:"3402 Kimball St, Heber, AZ 85928",phone:"(909) 531-3582",website:"https://heberovergaard.org/member-directory/",image:img("photo-1441986300917-64674bd600d8")},
{id:"b43",name:"Overgaard Market",slug:"overgaard-market",category:"Shopping",shortDescription:"Neighborhood market on Mogollon Drive.",description:"A neighborhood market serving Overgaard residents and visitors. Confirm current products and hours directly.",address:"2737 Mogollon Dr, Overgaard, AZ 85933",phone:"(928) 535-4681",website:"https://heberovergaard.org/member-directory/",image:img("photo-1578916171728-46686eac8d58")},
{id:"b44",name:"Pots Plus",slug:"pots-plus",category:"Shopping",shortDescription:"Local retail shop on Highway 260.",description:"A local retail business listed by the Heber-Overgaard Chamber. Contact the business directly for current merchandise and hours.",address:"2955 Hwy 260 Ste D, Overgaard, AZ 85933",phone:"(928) 240-1638",website:"https://heberovergaard.org/member-directory/",image:img("photo-1618220179428-22790b461013")},
{id:"b45",name:"Rim Country Senior Center",slug:"rim-country-senior-center",category:"Professional Services",shortDescription:"Community senior center in Overgaard.",description:"A local senior center serving the Rim Country community. Contact the center for current programs, meals, events, and hours.",address:"2171 B St, Overgaard, AZ 85933",phone:"(928) 535-5525",website:"https://heberovergaard.org/member-directory/",image:img("photo-1573496359142-b8d87734a5a2")}
];
export const attractions:Attraction[]=[
{id:"a1",name:"Tall Timbers Park",slug:"tall-timbers-park",category:"Parks",description:"A public Navajo County park in Heber-Overgaard and a community gathering place. Check current access and event use before visiting.",image:img("photo-1500530855697-b586d89ba3ee"),costType:"Free",featured:true},
{id:"a2",name:"Mogollon Rim",slug:"mogollon-rim",category:"Scenic",description:"A dramatic forested escarpment with broad viewpoints, scenic drives, trails, and seasonal recreation access.",image:"/images/town/winter-rim.jpg",costType:"Free",featured:true},
{id:"a3",name:"Rock House Museum",slug:"rock-house-museum",category:"Historic",description:"A local-history stop highlighted by the Heber-Overgaard Chamber. Verify opening dates and hours before visiting.",image:img("photo-1529107386315-e1a2ed48a620"),costType:"Varies"},
{id:"a4",name:"Rim Community Library",slug:"rim-community-library",category:"Family Activities",description:"Community library providing access to information, a community room, and a welcoming indoor stop.",image:img("photo-1521587760476-6c12a4b040da"),costType:"Free"},
{id:"a5",name:"Woods Canyon Lake",slug:"woods-canyon-lake",category:"Lakes",description:"A popular Mogollon Rim lake recreation area for fishing, picnicking, camping, and nearby trails. Lake access is free; licenses, camping, rentals, or optional services may cost extra.",image:img("photo-1439853949127-fa647821eba0"),costType:"Free"},
{id:"a6",name:"Willow Springs Lake",slug:"willow-springs-lake",category:"Lakes",description:"A 150-acre trout lake set among tall pines at 7,600 feet. Day use and boat launching are free; anglers still need the appropriate Arizona fishing license.",image:img("photo-1500534623283-312aade485b7"),website:"https://www.fs.usda.gov/r03/apache-sitgreaves/recreation/willow-springs-lake-fishing-and-boating-site",costType:"Free",featured:true},
{id:"a7",name:"Black Canyon Lake",slug:"black-canyon-lake",category:"Lakes",description:"A free-to-visit Black Mesa Ranger District lake south of Heber-Overgaard. Access can be seasonal; check alerts and road conditions. Fishing licenses and optional services are separate.",image:img("photo-1470252649378-9c29740c9fa8"),costType:"Free"},
{id:"a8",name:"Apache-Sitgreaves National Forests",slug:"apache-sitgreaves",category:"Recreation",description:"The surrounding national forest offers free hiking, scenic viewing, and wildlife watching. Permits, developed camping, rentals, and licenses may cost extra.",image:"/images/town/ponderosa-forest.jpg",costType:"Free"}
];
export const trails:Trail[]=[
{id:"t1",name:"Rim Vista Trail",slug:"rim-vista-trail",description:"A paved, accessible Rim trail connecting scenic overlooks, campground areas, and Woods Canyon Lake recreation facilities.",distance:"3+ mi",difficulty:"Easy",duration:"1–2 hr",activityType:"Scenic",familyFriendly:true,image:img("photo-1551632811-561732d1e306"),officialUrl:"https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5380979.pdf",directionsUrl:"https://www.google.com/maps/search/?api=1&query=Rim+Vista+Trail+Woods+Canyon+Lake+Arizona"},
{id:"t2",name:"235 Road Trail",slug:"235-road-trail",description:"A non-motorized trail in a designated wildlife habitat area, used for hiking, horseback riding, and mountain biking.",distance:"Verify locally",difficulty:"Moderate",duration:"Varies",activityType:"Hiking",familyFriendly:false,image:img("photo-1464822759023-fed622ff2c3b"),officialUrl:"https://www.fs.usda.gov/recarea/asnf/recarea/?recid=45157",directionsUrl:"https://www.google.com/maps/search/?api=1&query=235+Road+Trail+Forest+Lakes+Arizona"},
{id:"t3",name:"237 B OHV Trail",slug:"237-b-ohv-trail",description:"A short Forest Service OHV connector from the 237 B Trailhead to Larson Canyon Trail for vehicles up to 68 inches wide.",distance:"0.5 mi",difficulty:"Moderate",duration:"Varies",activityType:"ATV",familyFriendly:false,image:img("photo-1500534314209-a25ddb2bd429"),officialUrl:"https://www.fs.usda.gov/recarea/asnf/recarea/?recid=45157",directionsUrl:"https://www.google.com/maps/search/?api=1&query=237+B+Trailhead+Forest+Lakes+Arizona"},
{id:"t4",name:"99a OHV Trail",slug:"99a-ohv-trail",description:"An ATV route beginning at Wildcat Road Access in Forest Lakes and ending at Forest Road 172.",distance:"3.9 mi",difficulty:"Moderate",duration:"Varies",activityType:"ATV",familyFriendly:false,image:img("photo-1501554728187-ce583db33af7"),officialUrl:"https://www.fs.usda.gov/recarea/asnf/recarea/?recid=45157",directionsUrl:"https://www.google.com/maps/search/?api=1&query=99A+OHV+Trail+Forest+Lakes+Arizona"},
{id:"t5",name:"Woods Canyon Lake Trail",slug:"woods-canyon-lake-trail",description:"A lake-area walking route through ponderosa forest. Confirm the current official route, access, and seasonal conditions before setting out.",distance:"Verify locally",difficulty:"Easy",duration:"Varies",activityType:"Hiking",familyFriendly:true,image:img("photo-1500534623283-312aade485b7"),officialUrl:"https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/fsbdev7_012510.pdf",directionsUrl:"https://www.google.com/maps/search/?api=1&query=Woods+Canyon+Lake+Trail+Arizona"},
{id:"t6",name:"General Crook National Recreation Trail",slug:"general-crook-national-recreation-trail",description:"A historic long-distance route following portions of the Mogollon Rim. Choose and plan a specific segment using the official Forest Service map before setting out.",distance:"Choose a segment",difficulty:"Moderate",duration:"Varies",activityType:"Hiking",familyFriendly:false,image:img("photo-1464278533981-50106e6176b1"),officialUrl:"https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/fseprd1000480.pdf",directionsUrl:"https://www.google.com/maps/search/?api=1&query=General+Crook+National+Recreation+Trail+Mogollon+Rim+Arizona"}
];
export const events:Event[]=[];
export const deals:Deal[]=[];
export const categories=["Things To Do","Eat & Drink","Free Things","Trails","Events","Shop Local","Places To Stay","Local Deals"];
