import {getSupabase} from "@/lib/supabase/server";
import {safeExternalUrl} from "@/lib/listings";

export const RENTAL_AGREEMENT_VERSION="2026-09-15";
export const DEFAULT_RENTAL_PRICE_CENTS=7900;
export const RENTAL_AGREEMENT_LAST_UPDATED="September 15, 2026";
export const RENTAL_AGREEMENT_TEXT=`Vacation Rental Advertising Terms/Agreement\nVersion: ${RENTAL_AGREEMENT_VERSION}\nLast updated: ${RENTAL_AGREEMENT_LAST_UPDATED}\n\nTownGuide provides advertising only and is not a property manager, booking service, broker, or party to any reservation. Availability, pricing, payments, refunds, cancellations, guest communication, disputes, and property information are handled by the property owner or booking platform.\n\nThe advertiser confirms that they own the property or are authorized to advertise it; have permission to submit and authorize use of all photos and written content; and that the rental complies with applicable licensing, registration, tax, HOA, safety, and short-term-rental requirements.\n\nEach purchase covers one property for one year beginning on the approved listing's advertising start date and includes one listing update during that paid year. TownGuide charges no booking commission. Publication requires administrative review and approval.\n\nRequests for advertising credit or rescheduling may only be made and granted during the first three calendar days of the agreed advertising period and require approval. No advertising credit or rescheduling is available after those three days. Approved credits expire six months after the original advertising start date. Rescheduling is subject to placement availability. The separate full-refund policy remains in effect.`;

export type PublicVacationRental={id:string;property_name:string;slug:string;location:string;general_area:string|null;property_type:string;short_description:string;description:string;max_guests:number;bedrooms:number;bathrooms:number;pet_friendly:boolean;amenities:string[];highlights:string[];airbnb_url:string|null;vrbo_url:string|null;direct_booking_url:string|null;approximate_latitude:number|null;approximate_longitude:number|null;map_is_approximate:boolean;featured_image_url:string|null;photo_urls:string[];featured:boolean;advertising_start_date:string;advertising_expires_at:string;updated_at:string};

function platformUrl(value:unknown,domains:string[]){const safe=safeExternalUrl(value);if(!safe)return undefined;const host=new URL(safe).hostname.toLowerCase();return domains.some(domain=>host===domain||host.endsWith(`.${domain}`))?safe:undefined;}
export function validateRentalUrls(values:{airbnb?:unknown;vrbo?:unknown;direct?:unknown}){const urls={airbnb:platformUrl(values.airbnb,["airbnb.com","airbnb.co.uk","airbnb.ca"]),vrbo:platformUrl(values.vrbo,["vrbo.com"]),direct:safeExternalUrl(values.direct)};return {urls,valid:!!(urls.airbnb||urls.vrbo||urls.direct)};}
export function validateRentalImages(files:File[]){if(files.length<1||files.length>10)return "Upload between 1 and 10 photos.";for(const file of files){if(file.size>5*1024*1024)return "Each photo must be 5 MB or smaller.";if(!["image/jpeg","image/png","image/webp"].includes(file.type))return "Photos must be JPG, PNG, or WebP files.";}return null;}
export function splitList(value:unknown,max=30){return String(value||"").split(/[\n,]/).map(x=>x.trim()).filter(Boolean).slice(0,max);}
export async function getPublicVacationRentals(){const db=await getSupabase();if(!db)return [] as PublicVacationRental[];const {data,error}=await db.from("public_vacation_rentals").select("*").order("featured",{ascending:false}).order("property_name");if(error){console.error("Unable to load vacation rentals",error.message);return []}return data as PublicVacationRental[];}
export async function getPublicVacationRental(slug:string){const db=await getSupabase();if(!db)return null;const {data}=await db.from("public_vacation_rentals").select("*").eq("slug",slug).maybeSingle();return data as PublicVacationRental|null;}
