create extension if not exists pgcrypto;
create table public.businesses(id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,description text,short_description text,category text,address text,city text default 'Heber-Overgaard',state text default 'AZ',zip text,phone text,website text,email text,logo_url text,image_url text,latitude numeric,longitude numeric,hours_json jsonb default '{}',featured boolean default false,sponsored boolean default false,active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.attractions(id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,description text,category text,address text,latitude numeric,longitude numeric,image_url text,website text,phone text,cost_type text,featured boolean default false,active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.trails(id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,description text,distance text,difficulty text,estimated_duration text,activity_type text,family_friendly boolean default false,latitude numeric,longitude numeric,image_url text,directions_url text,active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.events(id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,description text,start_date date not null,end_date date,start_time time,location text,address text,image_url text,website text,category text,active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.deals(id uuid primary key default gen_random_uuid(),business_id uuid references public.businesses(id) on delete cascade,title text not null,description text,coupon_code text,start_date date,expiration_date date,image_url text,terms text,featured boolean default false,active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.qr_locations(id uuid primary key default gen_random_uuid(),code text unique not null,name text not null,business_id uuid references public.businesses(id) on delete set null,location_description text,active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.qr_scans(id bigint generated always as identity primary key,qr_location_id uuid not null references public.qr_locations(id) on delete cascade,scanned_at timestamptz default now(),device_type text,referrer text,user_agent text);
create index qr_scans_location_time_idx on public.qr_scans(qr_location_id,scanned_at desc);
create table public.analytics_events(id bigint generated always as identity primary key,event_type text not null,entity_type text,entity_id uuid,qr_location_id uuid references public.qr_locations(id) on delete set null,created_at timestamptz default now(),metadata_json jsonb default '{}');
create index analytics_type_time_idx on public.analytics_events(event_type,created_at desc);create index analytics_entity_idx on public.analytics_events(entity_type,entity_id);
create table public.business_inquiries(id uuid primary key default gen_random_uuid(),business_name text not null,contact_name text not null,phone text,email text not null,website text,category text,interest text,message text,status text default 'new',created_at timestamptz default now());
alter table public.businesses enable row level security;alter table public.attractions enable row level security;alter table public.trails enable row level security;alter table public.events enable row level security;alter table public.deals enable row level security;alter table public.qr_locations enable row level security;alter table public.qr_scans enable row level security;alter table public.analytics_events enable row level security;alter table public.business_inquiries enable row level security;
create policy "public reads active businesses" on public.businesses for select using(active);create policy "public reads active attractions" on public.attractions for select using(active);create policy "public reads active trails" on public.trails for select using(active);create policy "public reads active current events" on public.events for select using(active and coalesce(end_date,start_date)>=current_date);create policy "public reads active current deals" on public.deals for select using(active and (expiration_date is null or expiration_date>=current_date));
-- Authenticated dashboard users manage content. Production projects should add an admin-role claim check.
create policy "authenticated manages businesses" on public.businesses for all to authenticated using(true) with check(true);create policy "authenticated manages attractions" on public.attractions for all to authenticated using(true) with check(true);create policy "authenticated manages trails" on public.trails for all to authenticated using(true) with check(true);create policy "authenticated manages events" on public.events for all to authenticated using(true) with check(true);create policy "authenticated manages deals" on public.deals for all to authenticated using(true) with check(true);create policy "authenticated manages qr" on public.qr_locations for all to authenticated using(true) with check(true);create policy "authenticated reads scans" on public.qr_scans for select to authenticated using(true);create policy "authenticated reads analytics" on public.analytics_events for select to authenticated using(true);create policy "authenticated manages inquiries" on public.business_inquiries for all to authenticated using(true) with check(true);
