-- Hours audited August 23, 2026. The source is retained so future reviews are easy.
-- Listings without a dependable current schedule are intentionally left blank.

update public.businesses set hours_json=jsonb_build_object('display','Sun: 7 AM–9 PM\nMon–Thu: 7 AM–6 PM\nFri–Sat: 7 AM–9 PM','source','https://www.aztexaz.com/','verified_at','2026-08-23') where slug='aztec-coffee-taproom';
update public.businesses set hours_json=jsonb_build_object('display','Mon–Tue: Closed\nWed–Thu: 11 AM–8 PM\nFri–Sat: 11 AM–9 PM\nSun: 11 AM–8 PM','source','https://www.redoniononline.com/menu','verified_at','2026-08-23') where slug='red-onion-bar-grill';
update public.businesses set hours_json=jsonb_build_object('display','Daily: 7 AM–2 PM','source','https://findlocalcoffeeshops.com/arizona/heber-overgaard/store/sanders-coffee-co/','verified_at','2026-08-23') where slug='sanders-coffee-co';
update public.businesses set hours_json=jsonb_build_object('display','Front desk: Open 24 hours\nCheck-in: 3 PM\nCheck-out: 11 AM','source','https://www.bestwestern.com/en_US/book/heber/hotel-rooms/best-western-sawmill-inn/propertyCode.03123.html','verified_at','2026-08-23') where slug='best-western-sawmill-inn';
update public.businesses set hours_json=jsonb_build_object('display','Mon–Tue: 7 AM–2 PM\nWed: Closed\nThu–Sun: 7 AM–2 PM','source','https://www.tripadvisor.com/Restaurant_Review-g31242-d539029-Reviews-June_s_Cafe-Heber_Arizona.html','verified_at','2026-08-23') where slug='junes-cafe';
update public.businesses set hours_json=jsonb_build_object('display','Tue: Closed\nWed–Mon: 7 AM–2 PM','source','https://ponderosacafeaz.com/lunch','verified_at','2026-08-23') where slug='ponderosa-cafe';
update public.businesses set hours_json=jsonb_build_object('display','Mon–Wed: Closed\nThu: Noon–7 PM\nFri–Sat: Noon–8 PM\nSun: Noon–6 PM\nKitchen closes 15 minutes early.','source','https://www.pitstoppizzaaz.com/','verified_at','2026-08-23') where slug='pit-stop-pizza';
update public.businesses set hours_json=jsonb_build_object('display','Mon: Closed\nTue–Sun: 7 AM–2:30 PM','source','https://www.zmenu.com/three-bears-cafe-heber-online-menu/','verified_at','2026-08-23') where slug='three-bears-cafe';
update public.businesses set hours_json=jsonb_build_object('display','Mon–Wed: 7 AM–9 PM\nThu–Sat: 7 AM–10 PM\nSun: 8 AM–9 PM','source','https://www.restaurantji.com/az/heber-overgaard/alibertos-mexican-restaurant-/','verified_at','2026-08-23') where slug='alibertos-mexican-restaurant';
update public.businesses set hours_json=jsonb_build_object('display','Daily: 7 AM–8 PM','source','https://mymarketstores.com/heber/','verified_at','2026-08-23') where slug='the-market-at-heber';
update public.businesses set hours_json=jsonb_build_object('display','Daily: 11 AM–9 PM','source','https://www.tripadvisor.com/Restaurant_Review-g31242-d2317998-Reviews-Casa_Ramos-Heber_Arizona.html','verified_at','2026-08-23') where slug='casa-ramos';
update public.businesses set hours_json=jsonb_build_object('display','Mon–Sat: 8 AM–5 PM\nSun: 9 AM–4 PM','source','https://www.acehardware.com/store-details/11577','verified_at','2026-08-23') where slug='ace-hardware-overgaard';
update public.businesses set hours_json=jsonb_build_object('display','Sun: 11 AM–7 PM\nMon–Thu: 11 AM–8 PM\nFri–Sat: 11 AM–9 PM','source','https://order.toasttab.com/online/gigis-pizza-2767-hwy-260','verified_at','2026-08-23') where slug='gigis-pizza';
update public.businesses set hours_json=jsonb_build_object('display','Fri–Sat: 10 AM–5 PM\nSun: 9 AM–1 PM\nMon–Thu: Closed','source','https://maps.roadtrippers.com/us/overgaard-az/shopping/junk-warehouse-overgaard','verified_at','2026-08-23') where slug='junk-warehouse';
update public.businesses set hours_json=jsonb_build_object('display','Member access: Open 24 hours','source','https://www.bbb.org/us/az/overgaard/profile/fitness-center/mountain-top-fitness-gym-llc-1126-1000142404','verified_at','2026-08-23') where slug='mountain-top-fitness';
update public.businesses set hours_json=jsonb_build_object('display','Mon–Sat: 7 AM–5 PM\nSun: 10 AM–2 PM (parts only)','source','https://www.napaovergaard.com/contact','verified_at','2026-08-23') where slug='napa-of-overgaard';
update public.businesses set hours_json=jsonb_build_object('display','Office: Daily 9 AM–6 PM\nResort access: Open 24 hours','source','https://www.overgaardrvresort.com/contact','verified_at','2026-08-23') where slug='overgaard-rv-resort';
